name: build_deploy_aks
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      # - name: Login to DockerHub
      #   # if: github.event_name != 'pull_request'
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image: azure-vote-front
          folder: azure-vote
          branch: master
          tag: ${{ steps.meta.outputs.tags }}
      # - name: Azure login
      #   id: login
      #   uses: azure/login@v1.4.3
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: Set AKS context
      #   id: set-context
      #   uses: azure/aks-set-context@v3
      #   with:
      #     resource-group: "${{ secrets.resource_group }}"
      #     cluster-name: "${{ secrets.cluster_name }}"
      # - name: Setup kubectl
      #   id: install-kubectl
      #   uses: azure/setup-kubectl@v3
      # - name: Deploy to AKS
      #   id: deploy-aks
      #   uses: Azure/k8s-deploy@v4
      #   with:
      #     resource-group: "${{ secrets.resource_group }}"
      #     name: "${{ secrets.cluster_name }}"
      #     action: deploy
      #     strategy: basic
      #     private-cluster: true
      #     namespace: "development"
      #     manifests: |
      #       azure-vote-all-in-one-redis.yaml
      #     images: "${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}"
      #     pull-images: false
